Update pubspec.yaml
Innim/flutter_multiple_localization pull request #11
Opened 2023-05-11 18:39 UTC by muriloformiga

it solves pub get error:

Because multiple_localization 0.3.0 depends on intl ^0.17.0 and no versions of multiple_localization match >0.3.0 <0.4.0, multiple_localization ^0.3.0 requires intl ^0.17.0.
So, because micro_core depends on both intl ^0.18.1 and multiple_localization ^0.3.0, version solving failed.

2023-05-12 01:32 UTC, laogao commented
We're having the same problem and just about to file an issue. Glad this had been brought up and hopefully can be resolved soon. Kudos for the effort!

2023-05-12 14:12 UTC, stevenmetzger requested changes
It should be intl: ^0.18.0.

The caret sign (^) is used for [pub dependencies](https://www.dartlang.org/tools/pub/dependencies) in Dart to indicate a range of version numbers are allowed. Specifically, any version from the specified version up to (but not including) the next non-breaking version is ok.

So ^0.18.0 is okay for all versions >=0.18.0

https://stackoverflow.com/a/53563080

2023-05-12 14:20 UTC, stevenmetzger requested changes
Also the package version should probably be bumped up from 0.3.0 to 0.4.0 so we don't cause problems for users who still depend on intl ^0.17.0.

2023-05-22 15:22 UTC, greymag commented
@muriloformiga thank you for the PR. I just merged a similar #12 with more complex update changes, so I close this one.

2023-05-22 15:22 UTC, closed without merging